name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions:
  contents: write

jobs:
  lint:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4

    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 📦 Install ESLint v8 and dependencies
      run: |
        npm init -y
        npm install eslint@8 --save-dev

    - name: 🧹 Run ESLint with Auto-Fix on all folders
      run: |
        npx eslint secondChance-backend/**/*.js --fix || true
        npx eslint sentiment/**/*.js --fix || true
        npx eslint secondChance-frontend/**/*.js --fix || true

    - name: 🚀 Commit and Push changes if needed
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git diff --cached --quiet || git commit -m "🤖 Auto-fix: ESLint applied"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
